#############################################################################
# Makefile for building: clientGui
# Generated by qmake (2.01a) (Qt 4.8.3) on: mer. mars 12 18:41:08 2014
# Project:  clientGui.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile clientGui.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -Wextra -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Icommon -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = common/commAPI.cpp \
		common/HexagonalField.cpp \
		common/NetworkBase.cpp \
		common/NetworkInterface.cpp \
		clientMatchHandler.cpp \
		loginDialog.cpp \
		main.cpp \
		mainGui.cpp \
		selectionDialog.cpp \
		ticker.cpp \
		buildingsDialog.cpp \
		buildingsModel.cpp \
		playerMgr.cpp moc_loginDialog.cpp \
		moc_mainGui.cpp \
		moc_selectionDialog.cpp \
		moc_ticker.cpp \
		moc_buildingsDialog.cpp \
		moc_buildingsModel.cpp
OBJECTS       = commAPI.o \
		HexagonalField.o \
		NetworkBase.o \
		NetworkInterface.o \
		clientMatchHandler.o \
		loginDialog.o \
		main.o \
		mainGui.o \
		selectionDialog.o \
		ticker.o \
		buildingsDialog.o \
		buildingsModel.o \
		playerMgr.o \
		moc_loginDialog.o \
		moc_mainGui.o \
		moc_selectionDialog.o \
		moc_ticker.o \
		moc_buildingsDialog.o \
		moc_buildingsModel.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		common.pri \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		clientGui.pro
QMAKE_TARGET  = clientGui
DESTDIR       = 
TARGET        = clientGui

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: clientGui.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		common.pri \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile clientGui.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
common.pri:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile clientGui.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/clientGui1.0.0 || $(MKDIR) .tmp/clientGui1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/clientGui1.0.0/ && $(COPY_FILE) --parents common/commAPI.hpp common/Coordinates.hpp common/Defines.hpp common/HexagonalField.hpp common/NetworkBase.hpp common/NetworkInterface.hpp clientMatchHandler.hpp loginDialog.hpp mainGui.hpp selectionDialog.hpp ticker.hpp buildingsDialog.hpp buildingsModel.hpp playerMgr.hpp .tmp/clientGui1.0.0/ && $(COPY_FILE) --parents common/commAPI.cpp common/HexagonalField.cpp common/NetworkBase.cpp common/NetworkInterface.cpp clientMatchHandler.cpp loginDialog.cpp main.cpp mainGui.cpp selectionDialog.cpp ticker.cpp buildingsDialog.cpp buildingsModel.cpp playerMgr.cpp .tmp/clientGui1.0.0/ && (cd `dirname .tmp/clientGui1.0.0` && $(TAR) clientGui1.0.0.tar clientGui1.0.0 && $(COMPRESS) clientGui1.0.0.tar) && $(MOVE) `dirname .tmp/clientGui1.0.0`/clientGui1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/clientGui1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_loginDialog.cpp moc_mainGui.cpp moc_selectionDialog.cpp moc_ticker.cpp moc_buildingsDialog.cpp moc_buildingsModel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_loginDialog.cpp moc_mainGui.cpp moc_selectionDialog.cpp moc_ticker.cpp moc_buildingsDialog.cpp moc_buildingsModel.cpp
moc_loginDialog.cpp: common/NetworkInterface.hpp \
		common/Defines.hpp \
		loginDialog.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) loginDialog.hpp -o moc_loginDialog.cpp

moc_mainGui.cpp: ticker.hpp \
		common/NetworkInterface.hpp \
		common/Defines.hpp \
		mainGui.hpp \
		loginDialog.hpp \
		clientMatchHandler.hpp \
		Defines.hpp \
		selectionDialog.hpp \
		playerMgr.hpp \
		buildingsDialog.hpp \
		buildingsModel.hpp \
		mainGui.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainGui.hpp -o moc_mainGui.cpp

moc_selectionDialog.cpp: selectionDialog.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) selectionDialog.hpp -o moc_selectionDialog.cpp

moc_ticker.cpp: common/NetworkInterface.hpp \
		common/Defines.hpp \
		mainGui.hpp \
		ticker.hpp \
		loginDialog.hpp \
		clientMatchHandler.hpp \
		Defines.hpp \
		selectionDialog.hpp \
		playerMgr.hpp \
		buildingsDialog.hpp \
		buildingsModel.hpp \
		ticker.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ticker.hpp -o moc_ticker.cpp

moc_buildingsDialog.cpp: common/NetworkInterface.hpp \
		common/Defines.hpp \
		buildingsModel.hpp \
		mainGui.hpp \
		ticker.hpp \
		loginDialog.hpp \
		clientMatchHandler.hpp \
		Defines.hpp \
		selectionDialog.hpp \
		playerMgr.hpp \
		buildingsDialog.hpp \
		buildingsDialog.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) buildingsDialog.hpp -o moc_buildingsDialog.cpp

moc_buildingsModel.cpp: buildingsModel.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) buildingsModel.hpp -o moc_buildingsModel.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

commAPI.o: common/commAPI.cpp common/commAPI.hpp \
		common/Defines.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commAPI.o common/commAPI.cpp

HexagonalField.o: common/HexagonalField.cpp common/HexagonalField.hpp \
		common/Coordinates.hpp \
		common/Defines.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HexagonalField.o common/HexagonalField.cpp

NetworkBase.o: common/NetworkBase.cpp common/Defines.hpp \
		common/NetworkBase.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NetworkBase.o common/NetworkBase.cpp

NetworkInterface.o: common/NetworkInterface.cpp common/NetworkInterface.hpp \
		common/Defines.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NetworkInterface.o common/NetworkInterface.cpp

clientMatchHandler.o: clientMatchHandler.cpp clientMatchHandler.hpp \
		Defines.hpp \
		selectionDialog.hpp \
		common/NetworkInterface.hpp \
		common/Defines.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientMatchHandler.o clientMatchHandler.cpp

loginDialog.o: loginDialog.cpp loginDialog.hpp \
		common/NetworkInterface.hpp \
		common/Defines.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginDialog.o loginDialog.cpp

main.o: main.cpp mainGui.hpp \
		ticker.hpp \
		common/NetworkInterface.hpp \
		common/Defines.hpp \
		loginDialog.hpp \
		clientMatchHandler.hpp \
		Defines.hpp \
		selectionDialog.hpp \
		playerMgr.hpp \
		buildingsDialog.hpp \
		buildingsModel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainGui.o: mainGui.cpp mainGui.hpp \
		ticker.hpp \
		common/NetworkInterface.hpp \
		common/Defines.hpp \
		loginDialog.hpp \
		clientMatchHandler.hpp \
		Defines.hpp \
		selectionDialog.hpp \
		playerMgr.hpp \
		buildingsDialog.hpp \
		buildingsModel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainGui.o mainGui.cpp

selectionDialog.o: selectionDialog.cpp selectionDialog.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o selectionDialog.o selectionDialog.cpp

ticker.o: ticker.cpp ticker.hpp \
		common/NetworkInterface.hpp \
		common/Defines.hpp \
		mainGui.hpp \
		loginDialog.hpp \
		clientMatchHandler.hpp \
		Defines.hpp \
		selectionDialog.hpp \
		playerMgr.hpp \
		buildingsDialog.hpp \
		buildingsModel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ticker.o ticker.cpp

buildingsDialog.o: buildingsDialog.cpp buildingsDialog.hpp \
		common/NetworkInterface.hpp \
		common/Defines.hpp \
		buildingsModel.hpp \
		mainGui.hpp \
		ticker.hpp \
		loginDialog.hpp \
		clientMatchHandler.hpp \
		Defines.hpp \
		selectionDialog.hpp \
		playerMgr.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buildingsDialog.o buildingsDialog.cpp

buildingsModel.o: buildingsModel.cpp buildingsModel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buildingsModel.o buildingsModel.cpp

playerMgr.o: playerMgr.cpp playerMgr.hpp \
		Defines.hpp \
		selectionDialog.hpp \
		common/NetworkInterface.hpp \
		common/Defines.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playerMgr.o playerMgr.cpp

moc_loginDialog.o: moc_loginDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginDialog.o moc_loginDialog.cpp

moc_mainGui.o: moc_mainGui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainGui.o moc_mainGui.cpp

moc_selectionDialog.o: moc_selectionDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_selectionDialog.o moc_selectionDialog.cpp

moc_ticker.o: moc_ticker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ticker.o moc_ticker.cpp

moc_buildingsDialog.o: moc_buildingsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_buildingsDialog.o moc_buildingsDialog.cpp

moc_buildingsModel.o: moc_buildingsModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_buildingsModel.o moc_buildingsModel.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

