#ifndef DEFINES_HPP
#define DEFINES_HPP

#define PORT 3495
#define BACKLOG 20 //nbre max de clients dans la file d'attente
#define ERROR -1
#define INPUTSIZE 100 //taille du message envoyé du client vers le serveur
#define __DEBUG

#define TIMESCALE 1

#define USERNAME_LENGTH 30
#define PASSWORD_LENGTH 30

#define BAD_CONNECTION -1
#define NO_CHOICE -2

#define LOGIN_FAILED 0 
#define NORMAL_LOGIN 1
#define ADMIN_LOGIN 2

#define TICKETPRICE 40
#define VICTORYBONUS 35000
#define TIMESCALECONSTRUCTION 1
#define CONSTRUCTIONSTARTED 1
#define ALREADYINCONSTRUCTION 2
#define NOTENOUGHMONEY 3
#define NOTENOUGHAP 4

#define AP_TRAINING 5
#define AP_HOSPITAL 5
#define AP_UPGRADE 10
#define AP_FRIENDLY_MATCH 15
#define AP_AUCTION 3
#define AP_ENTER_AUCTION 5

#define GOLD_FOR_ONE_AP 10000 
#define TIMESCALEACTIONPOINTS 3

//TODO : regrouper les types de jeu sur un intervalle continu
#define SERVER_DOWN -1
#define LOGIN 1
#define LOGIN_CONFIRM 2
#define GETBUILDINGINFOS 3
#define BUILDINGINFOS 4
#define UPGRADE_BUILDING 5
#define UPGRADE_CONFIRM 6
#define PROPOSEMATCH 7
#define MATCH_CONFIRM 8
#define ACCEPTMATCH 9
//#define MATCH_CONFIRM 10
#define CREATEAUCTION 11
#define AUCTIONCREATION_CONFIRM 12
#define JOINAUCTION 13
#define AUCTIONJOIN_CONFIRM 14
#define GETMANAGERSLIST 15
#define MANAGERSLIST 16
#define GETAUCTIONSLIST 17
#define AUCTIONSLIST 18
#define GETPOSITIONS 19
#define POSITIONS 20
#define SELECTPLAYER 21 
#define PLAYERINFOS 22
#define MAKEMOVES 23
#define MOVES_CONFIRM 24
#define GETCURRENTPRICE 25
#define CURRENTPRICE 26
#define BID 27
#define BID_CONFIRM 28
#define TRAIN_PLAYER 29
#define TRAINING_STARTED 30
#define IS_MATCH_WAITING 31
#define MATCH_WAITING 32
#define CREATE_MANAGER 33
#define GETPLAYERSLIST 34
#define PLAYERSLIST 35
#define GETPLAYERINFOS 36
#define GETMANAGERINFOS 37
#define MANAGERINFOS 38
#define HEAL_PLAYER 39
#define HEAL_STARTED 40
#define END_AUCTION_TURN 41
#define AUCTION_RESULT 42
#define GETAUCTIONINFO 43
#define GET_AUCTION_PRICE 64
#define AUCTION_PRICE 65

#define MATCH_INVITATION 44
#define FORFEIT 45
#define OPPONENTFORFEIT 46
#define ASKFORDRAW 47
#define DRAW_CONFIRM 48
#define OPPONENTASKFORDRAW 49
#define ANSWERTODRAWPROPOSITION 50

#define START_PROMOTION 51
#define END_PROMOTION 52
#define RESULT_PROMOTION 53
#define BUY_ACTION_POINTS 54
#define PRICE_FOR_AP 55

#define CREATE_TOURNAMENT 56
#define NEWTOURNAMENT_CONFIRM 57
#define GETTOURNAMENTSLIST 58
#define TOURNAMENTSLIST 59
#define JOINTOURNAMENT 60
#define JOINTOURNAMENT_CONFIRM 61
#define MATCH_TOURNAMENT_START 62 //server to client
#define STARTTOURNAMENTMATCH 63 //client to server



#define STADIUM 1
#define TRAININGCENTER 2
#define HOSPITAL 3
#define FANSHOP 4
#define PROMOTIONCENTER 5
#define CONSTRUCTIONSTARTED 1
#define ALREADYINCONSTRUCTION 2
#define NOTENOUGHMONEY 3

#define SPEED 0
#define STRENGTH 1
#define PRECISION 2
#define REFLEX 3
#define RESISTANCE 4

#define NOT_ON_HEX_GRID -2
#define FREE_SPACE -1
#define TEAM1_KEEPER 0
#define TEAM1_SEEKER 1
#define TEAM1_CHASER1 2
#define TEAM1_CHASER2 3
#define TEAM1_CHASER3 4
#define TEAM1_BEATER1 5
#define TEAM1_BEATER2 6
#define TEAM2_KEEPER 7
#define TEAM2_SEEKER 8
#define TEAM2_CHASER1 9
#define TEAM2_CHASER2 10
#define TEAM2_CHASER3 11
#define TEAM2_BEATER1 12
#define TEAM2_BEATER2 13
#define GOLDENSNITCH 14
#define BLUDGER1 15
#define BLUDGER2 16
#define QUAFFLE 17

#define TEAM1_KEEPER_UNICODE "\u2780"
#define TEAM1_SEEKER_UNICODE "\u2781"
#define TEAM1_CHASER1_UNICODE "\u2782"
#define TEAM1_CHASER2_UNICODE "\u2783"
#define TEAM1_CHASER3_UNICODE "\u2784"
#define TEAM1_BEATER1_UNICODE "\u2785"
#define TEAM1_BEATER2_UNICODE "\u2786"
#define TEAM2_KEEPER_UNICODE "\u278A"
#define TEAM2_SEEKER_UNICODE "\u278B"
#define TEAM2_CHASER1_UNICODE "\u278C"
#define TEAM2_CHASER2_UNICODE "\u278D"
#define TEAM2_CHASER3_UNICODE "\u278E"
#define TEAM2_BEATER1_UNICODE "\u278F"
#define TEAM2_BEATER2_UNICODE "\u2790"
#define GOLDENSNITCH_UNICODE "\u2A00"
#define BLUDGER1_UNICODE "\u2A01"
#define BLUDGER2_UNICODE "\u2A01"
#define QUAFFLE_UNICODE "\u2B24"
#define FREE_SPACE_UNICODE "\u2B1C"
#define GOAL_UNICODE "\u2A02"

#define GOAL_SIDE1_DIAG -9
#define GOAL_SIDE1_LINE 0
#define GOAL_SIDE2_DIAG 9
#define GOAL_SIDE2_LINE 0

#define ROLE_KEEPER 0
#define ROLE_SEEKER 1
#define ROLE_CHASER 2
#define ROLE_BEATER 3

#define NO_SPECIAL_ACTION -1
#define INTERCEPT_QUAFFLE 0
#define CATCH_GOLDENSNITCH 1

//TODO : définir les positions de départ en fonction de la taille du terrain
//TODO : plusieurs buts quand grand terrain
//TODO : position de départ du vif d'or et des bugler aléatoire



#define STARTINGDIAG_QUAFFLE 0
#define STARTINGLINE_QUAFFLE 0

#define STARTINGDIAG_BLUDGER1 3
#define STARTINGLINE_BLUDGER1 5

#define STARTINGDIAG_BLUDGER2 -3
#define STARTINGLINE_BLUDGER2 -5

#define STARTINGDIAG_GOLDENSNITCH 2
#define STARTINGLINE_GOLDENSNITCH -3



#define STARTINGDIAG_TEAM1_KEEPER -8
#define STARTINGLINE_TEAM1_KEEPER 0

#define STARTINGDIAG_TEAM1_SEEKER -9
#define STARTINGLINE_TEAM1_SEEKER 9

#define STARTINGDIAG_TEAM1_CHASER1 0
#define STARTINGLINE_TEAM1_CHASER1 -6

#define STARTINGDIAG_TEAM1_CHASER2 -3
#define STARTINGLINE_TEAM1_CHASER2 0

#define STARTINGDIAG_TEAM1_CHASER3 -6
#define STARTINGLINE_TEAM1_CHASER3 6

#define STARTINGDIAG_TEAM1_BEATER1 1
#define STARTINGLINE_TEAM1_BEATER1  -5

#define STARTINGDIAG_TEAM1_BEATER2 -4
#define STARTINGLINE_TEAM1_BEATER2 5

#define STARTINGDIAG_TEAM2_KEEPER 8
#define STARTINGLINE_TEAM2_KEEPER 0

#define STARTINGDIAG_TEAM2_SEEKER 9
#define STARTINGLINE_TEAM2_SEEKER -9
 
#define STARTINGDIAG_TEAM2_CHASER1 6
#define STARTINGLINE_TEAM2_CHASER1 -6

#define STARTINGDIAG_TEAM2_CHASER2 3
#define STARTINGLINE_TEAM2_CHASER2 0

#define STARTINGDIAG_TEAM2_CHASER3 0
#define STARTINGLINE_TEAM2_CHASER3 6

#define STARTINGDIAG_TEAM2_BEATER1 4
#define STARTINGLINE_TEAM2_BEATER1 -5

#define STARTINGDIAG_TEAM2_BEATER2 -1
#define STARTINGLINE_TEAM2_BEATER2 5



//codes de confirmation : 
#define MATCH_STARTING 0
#define INVITATION_NOT_POSSIBLE 1
#define MATCH_DENIED 2
#define DRAWACCEPTED 3
#define DRAWDENIED 4
#define TOURNAMENT_JOINED 5
#define TOURNAMENT_NOT_JOINED 6

#endif
